### PR TITLE
Replace current saliency map generation with Recipro-CAM for cls

### PR DESCRIPTION
**Pull request by negvet**
Support ReciproCAM explain algorithm (class discriminative algorithm)
https://arxiv.org/pdf/2209.14074.pdf

Replace current SaliencyMap with ReciproCAM.

Related PR: https://github.com/openvinotoolkit/training_extensions/pull/1363

TODO:
- [x] Benchmark

### CODE REVIEW

**Review by goodsong81 — COMMENTED** [review]
Except for the algorithm implementation itself, it looks good to me.
One question regarding the algorithm is whether it produces semantically correct per-label saliency maps for multi-label and hierarchical label classification, too. Could you confirm?

**Comment by negvet** [comment]
> Except for the algorithm implementation itself, it looks good to me. One question regarding the algorithm is whether it produces semantically correct per-label saliency maps for multi-label and hierarchical label classification, too. Could you confirm?

Please see per-class saliency maps for multi-label settings:
image

The algorithm do not support hierarchical label classification for now. Probably it is possible to generate saliency maps for every head that we can have (for the hierarchical cls). But I propose to separate this.

**Comment by goodsong81** [comment]
Multi-label looks fine to me. Thank you for the example :)
BTW, how do we support h-label in this PR, then? Is it providing legacy 1 saliency map for h-label?

**Comment by negvet** [comment]
> Multi-label looks fine to me. Thank you for the example :) BTW, how do we support h-label in this PR, then? Is it providing legacy 1 saliency map for h-label?

For the h-label case, current implementation support explanation of the bottom-level classes

**Review by goodsong81 — APPROVED** [review]
LGTM.

**Comment by goodsong81** [comment]
> > Multi-label looks fine to me. Thank you for the example :) BTW, how do we support h-label in this PR, then? Is it providing legacy 1 saliency map for h-label?
> 
> For the h-label case, current implementation support explanation of the bottom-level classes

OK to me. :)

**Comment by harimkang** [comment]
This seems to be a PR for the `develop` target. Doesn't this have to be the same for the `otx` branch (for otx feature/otx branch)?

**Comment by goodsong81** [comment]
> This seems to be a PR for the `develop` target. Doesn't this have to be the same for the `otx` branch (for otx feature/otx branch)?

This PR is saliency map enhancement for Geti1.1 -> OTE/develop (MPA/develop)
Similary detection PR will be followed.
Dongkwan's PRs are CLI XAI for OTE1.0.0 -> Geti1.3? -> OTE/feature/otx (MPA/otx)

**Pull request merged**
