### PR TITLE
Cythonize AugMixAugment

### PR DESCRIPTION
**Pull request by vinnamkim**
- Cythonize AugMixAugment
 - Add unit tests

### CODE REVIEW

**Comment by sovrasov** [comment]
Hi @vinnamkim! Could you please provide some data about the performance improvement that brings the cythonized code?

**Review by goodsong81 — CHANGES_REQUESTED** [review]
Thank you for the update. BTW, we've recently merged MPA otx branch to OTE feature/otx branch. https://github.com/openvinotoolkit/training_extensions/pull/1464.
Could you retarget this PR to OTE repo?

**Comment by vinnamkim** [comment]
> Hi @vinnamkim! Could you please provide some data about the performance improvement that brings the cythonized code?

Hi, I sent you page links about it on Teams. Please feel free to ask me if you have questions.

**Comment by vinnamkim** [comment]
> Thank you for the update. BTW, we've recently merged MPA otx branch to OTE feature/otx branch. [openvinotoolkit/training_extensions#1464](https://github.com/openvinotoolkit/training_extensions/pull/1464). Could you retarget this PR to OTE repo?

I changed this PR's target branch to apply this change to OTE 0.5.0 `develop` branch, and I'll also make another PR in OTE repo for `feature/otx` branch.

**Comment by goodsong81** [comment]
> > Thank you for the update. BTW, we've recently merged MPA otx branch to OTE feature/otx branch. [openvinotoolkit/training_extensions#1464](https://github.com/openvinotoolkit/training_extensions/pull/1464). Could you retarget this PR to OTE repo?
> 
> I changed this PR's target branch to apply this change to OTE 0.5.0 `develop` branch, and I'll also make another PR in OTE repo for `feature/otx` branch.

Thank you Vinnam. Then, would you create yet another PR to OTE develop branch to change MPA commit? At least, I'd recommend to create a draft PR to execute OTE CI with this change. (OTE feature/otx branch will run github action CI test.)

**Review by sungmanc — APPROVED** [review]
This PR is related to OTEv0.5.0 and there are no FAIL cases in CI tests.
Report is here: http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-866&environment=iotg-dev-workstation-08

And there is also another PR to target the `feature/otx` branch. So, we can merge this PR. What do you think? @goodsong81

**Review by wonjuleee — APPROVED** [review]
Looks good to me

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
